package ghidraxbe;

import java.util.ArrayList;
import java.util.List;

import ghidra.program.model.address.Address;
import ghidra.program.model.address.AddressOutOfBoundsException;
import ghidra.program.model.mem.Memory;
import ghidra.program.model.mem.MemoryAccessException;

/**
 * The thunk table lists all kernel imports used by an XBE.
 *
 * @author Jonas Schievink
 */
public class ThunkTable {
    /**
     * A thunk table entry.
     *
     * Contains ID (ordinal) and name of the import it references, as well as its
     * address in virtual memory.
     *
     * @author Jonas Schievink
     */
    public static class Entry {
	private int ordinal;
	private int address;
	private String name;

	private Entry(int address, int ordinal, String name) {
	    this.address = address;
	    this.ordinal = ordinal;
	    this.name = name;
	}

	public int ordinal() {
	    return this.ordinal;
	}

	public int address() {
	    return this.address;
	}

	public String name() {
	    return this.name;
	}

	@Override
	public String toString() {
	    return String.format("#%d @ %x: %s", ordinal, address, name);
	}
    }

    private List<Entry> entries;

    /**
     * Parses a thunk table from virtual memory.
     *
     * @param startAddr Starting address of the thunk table, decoded from the XBE
     *                  header
     * @param mem       Virtual memory holding the XBE sections
     * @throws MemoryAccessException
     * @throws AddressOutOfBoundsException
     */
    public ThunkTable(Address startAddr, Memory mem) throws MemoryAccessException, AddressOutOfBoundsException {
	this.entries = new ArrayList<>();

	Address addr = startAddr;
	int ordinal;
	while ((ordinal = mem.getInt(addr)) != 0) {
	    addr = addr.add(4);
	    ordinal &= 0x1ff; // up to 512

	    String name;
	    if (symbols.length <= ordinal) {
		// Unknown
		name = "Unknown" + ordinal;
	    } else {
		name = symbols[ordinal];
	    }

	    this.entries.add(new Entry((int) (startAddr.getOffset()) + this.entries.size() * 4, ordinal, name));
	}
    }

    public List<Entry> entries() {
	return this.entries;
    }

    private static final String[] symbols = {
	"Unused0",
	"AvGetSavedDataAddress",
	"AvSendTVEncoderOption",
	"AvSetDisplayMode",
	"AvSetSavedDataAddress",
	"DbgBreakPoint",
	"DbgBreakPointWithStatus",
	"DbgLoadImageSymbols",
	"DbgPrint",
	"HalReadSMCTrayState",
	"DbgPrompt",
	"DbgUnLoadImageSymbols",
	"ExAcquireReadWriteLockExclusive",
	"ExAcquireReadWriteLockShared",
	"ExAllocatePool",
	"ExAllocatePoolWithTag",
	"ExEventObjectType",
	"ExFreePool",
	"ExInitializeReadWriteLock",
	"ExInterlockedAddLargeInteger",
	"ExInterlockedAddLargeStatistic",
	"ExInterlockedCompareExchange64",
	"ExMutantObjectType",
	"ExQueryPoolBlockSize",
	"ExQueryNonVolatileSetting",
	"ExReadWriteRefurbInfo",
	"ExRaiseException",
	"ExRaiseStatus",
	"ExReleaseReadWriteLock",
	"ExSaveNonVolatileSetting",
	"ExSemaphoreObjectType",
	"ExTimerObjectType",
	"ExfInterlockedInsertHeadList",
	"ExfInterlockedInsertTailList",
	"ExfInterlockedRemoveHeadList",
	"FscGetCacheSize",
	"FscInvalidateIdleBlocks",
	"FscSetCacheSize",
	"HalClearSoftwareInterrupt",
	"HalDisableSystemInterrupt",
	"HalDiskCachePartitionCount",
	"HalDiskModelNumber",
	"HalDiskSerialNumber",
	"HalEnableSystemInterrupt",
	"HalGetInterruptVector",
	"HalReadSMBusValue",
	"HalReadWritePCISpace",
	"HalRegisterShutdownNotification",
	"HalRequestSoftwareInterrupt",
	"HalReturnToFirmware",
	"HalWriteSMBusValue",
	"InterlockedCompareExchange",
	"InterlockedDecrement",
	"InterlockedIncrement",
	"InterlockedExchange",
	"InterlockedExchangeAdd",
	"InterlockedFlushSList",
	"InterlockedPopEntrySList",
	"InterlockedPushEntrySList",
	"IoAllocateIrp",
	"IoBuildAsynchronousFsdRequest",
	"IoBuildDeviceIoControlRequest",
	"IoBuildSynchronousFsdRequest",
	"IoCheckShareAccess",
	"IoCompletionObjectType",
	"IoCreateDevice",
	"IoCreateFile",
	"IoCreateSymbolicLink",
	"IoDeleteDevice",
	"IoDeleteSymbolicLink",
	"IoDeviceObjectType",
	"IoFileObjectType",
	"IoFreeIrp",
	"IoInitializeIrp",
	"IoInvalidDeviceRequest",
	"IoQueryFileInformation",
	"IoQueryVolumeInformation",
	"IoQueueThreadIrp",
	"IoRemoveShareAccess",
	"IoSetIoCompletion",
	"IoSetShareAccess",
	"IoStartNextPacket",
	"IoStartNextPacketByKey",
	"IoStartPacket",
	"IoSynchronousDeviceIoControlRequest",
	"IoSynchronousFsdRequest",
	"IofCallDriver",
	"IofCompleteRequest",
	"KdDebuggerEnabled",
	"KdDebuggerNotPresent",
	"IoDismountVolume",
	"IoDismountVolumeByName",
	"KeAlertResumeThread",
	"KeAlertThread",
	"KeBoostPriorityThread",
	"KeBugCheck",
	"KeBugCheckEx",
	"KeCancelTimer",
	"KeConnectInterrupt",
	"KeDelayExecutionThread",
	"KeDisconnectInterrupt",
	"KeEnterCriticalRegion",
	"MmGlobalData",
	"KeGetCurrentIrql",
	"KeGetCurrentThread",
	"KeInitializeApc",
	"KeInitializeDeviceQueue",
	"KeInitializeDpc",
	"KeInitializeEvent",
	"KeInitializeInterrupt",
	"KeInitializeMutant",
	"KeInitializeQueue",
	"KeInitializeSemaphore",
	"KeInitializeTimerEx",
	"KeInsertByKeyDeviceQueue",
	"KeInsertDeviceQueue",
	"KeInsertHeadQueue",
	"KeInsertQueue",
	"KeInsertQueueApc",
	"KeInsertQueueDpc",
	"KeInterruptTime",
	"KeIsExecutingDpc",
	"KeLeaveCriticalRegion",
	"KePulseEvent",
	"KeQueryBasePriorityThread",
	"KeQueryInterruptTime",
	"KeQueryPerformanceCounter",
	"KeQueryPerformanceFrequency",
	"KeQuerySystemTime",
	"KeRaiseIrqlToDpcLevel",
	"KeRaiseIrqlToSynchLevel",
	"KeReleaseMutant",
	"KeReleaseSemaphore",
	"KeRemoveByKeyDeviceQueue",
	"KeRemoveDeviceQueue",
	"KeRemoveEntryDeviceQueue",
	"KeRemoveQueue",
	"KeRemoveQueueDpc",
	"KeResetEvent",
	"KeRestoreFloatingPointState",
	"KeResumeThread",
	"KeRundownQueue",
	"KeSaveFloatingPointState",
	"KeSetBasePriorityThread",
	"KeSetDisableBoostThread",
	"KeSetEvent",
	"KeSetEventBoostPriority",
	"KeSetPriorityProcess",
	"KeSetPriorityThread",
	"KeSetTimer",
	"KeSetTimerEx",
	"KeStallExecutionProcessor",
	"KeSuspendThread",
	"KeSynchronizeExecution",
	"KeSystemTime",
	"KeTestAlertThread",
	"KeTickCount",
	"KeTimeIncrement",
	"KeWaitForMultipleObjects",
	"KeWaitForSingleObject",
	"KfRaiseIrql",
	"KfLowerIrql",
	"KiBugCheckData",
	"KiUnlockDispatcherDatabase",
	"LaunchDataPage",
	"MmAllocateContiguousMemory",
	"MmAllocateContiguousMemoryEx",
	"MmAllocateSystemMemory",
	"MmClaimGpuInstanceMemory",
	"MmCreateKernelStack",
	"MmDeleteKernelStack",
	"MmFreeContiguousMemory",
	"MmFreeSystemMemory",
	"MmGetPhysicalAddress",
	"MmIsAddressValid",
	"MmLockUnlockBufferPages",
	"MmLockUnlockPhysicalPage",
	"MmMapIoSpace",
	"MmPersistContiguousMemory",
	"MmQueryAddressProtect",
	"MmQueryAllocationSize",
	"MmQueryStatistics",
	"MmSetAddressProtect",
	"MmUnmapIoSpace",
	"NtAllocateVirtualMemory",
	"NtCancelTimer",
	"NtClearEvent",
	"NtClose",
	"NtCreateDirectoryObject",
	"NtCreateEvent",
	"NtCreateFile",
	"NtCreateIoCompletion",
	"NtCreateMutant",
	"NtCreateSemaphore",
	"NtCreateTimer",
	"NtDeleteFile",
	"NtDeviceIoControlFile",
	"NtDuplicateObject",
	"NtFlushBuffersFile",
	"NtFreeVirtualMemory",
	"NtFsControlFile",
	"NtOpenDirectoryObject",
	"NtOpenFile",
	"NtOpenSymbolicLinkObject",
	"NtProtectVirtualMemory",
	"NtPulseEvent",
	"NtQueueApcThread",
	"NtQueryDirectoryFile",
	"NtQueryDirectoryObject",
	"NtQueryEvent",
	"NtQueryFullAttributesFile",
	"NtQueryInformationFile",
	"NtQueryIoCompletion",
	"NtQueryMutant",
	"NtQuerySemaphore",
	"NtQuerySymbolicLinkObject",
	"NtQueryTimer",
	"NtQueryVirtualMemory",
	"NtQueryVolumeInformationFile",
	"NtReadFile",
	"NtReadFileScatter",
	"NtReleaseMutant",
	"NtReleaseSemaphore",
	"NtRemoveIoCompletion",
	"NtResumeThread",
	"NtSetEvent",
	"NtSetInformationFile",
	"NtSetIoCompletion",
	"NtSetSystemTime",
	"NtSetTimerEx",
	"NtSignalAndWaitForSingleObjectEx",
	"NtSuspendThread",
	"NtUserIoApcDispatcher",
	"NtWaitForSingleObject",
	"NtWaitForSingleObjectEx",
	"NtWaitForMultipleObjectsEx",
	"NtWriteFile",
	"NtWriteFileGather",
	"NtYieldExecution",
	"ObCreateObject",
	"ObDirectoryObjectType",
	"ObInsertObject",
	"ObMakeTemporaryObject",
	"ObOpenObjectByName",
	"ObOpenObjectByPointer",
	"ObpObjectHandleTable",
	"ObReferenceObjectByHandle",
	"ObReferenceObjectByName",
	"ObReferenceObjectByPointer",
	"ObSymbolicLinkObjectType",
	"ObfDereferenceObject",
	"ObfReferenceObject",
	"PhyGetLinkState",
	"PhyInitialize",
	"PsCreateSystemThread",
	"PsCreateSystemThreadEx",
	"PsQueryStatistics",
	"PsSetCreateThreadNotifyRoutine",
	"PsTerminateSystemThread",
	"PsThreadObjectType",
	"RtlAnsiStringToUnicodeString",
	"RtlAppendStringToString",
	"RtlAppendUnicodeStringToString",
	"RtlAppendUnicodeToString",
	"RtlAssert",
	"RtlCaptureContext",
	"RtlCaptureStackBackTrace",
	"RtlCharToInteger",
	"RtlCompareMemory",
	"RtlCompareMemoryUlong",
	"RtlCompareString",
	"RtlCompareUnicodeString",
	"RtlCopyString",
	"RtlCopyUnicodeString",
	"RtlCreateUnicodeString",
	"RtlDowncaseUnicodeChar",
	"RtlDowncaseUnicodeString",
	"RtlEnterCriticalSection",
	"RtlEnterCriticalSectionAndRegion",
	"RtlEqualString",
	"RtlEqualUnicodeString",
	"RtlExtendedIntegerMultiply",
	"RtlExtendedLargeIntegerDivide",
	"RtlExtendedMagicDivide",
	"RtlFillMemory",
	"RtlFillMemoryUlong",
	"RtlFreeAnsiString",
	"RtlFreeUnicodeString",
	"RtlGetCallersAddress",
	"RtlInitAnsiString",
	"RtlInitUnicodeString",
	"RtlInitializeCriticalSection",
	"RtlIntegerToChar",
	"RtlIntegerToUnicodeString",
	"RtlLeaveCriticalSection",
	"RtlLeaveCriticalSectionAndRegion",
	"RtlLowerChar",
	"RtlMapGenericMask",
	"RtlMoveMemory",
	"RtlMultiByteToUnicodeN",
	"RtlMultiByteToUnicodeSize",
	"RtlNtStatusToDosError",
	"RtlRaiseException",
	"RtlRaiseStatus",
	"RtlTimeFieldsToTime",
	"RtlTimeToTimeFields",
	"RtlTryEnterCriticalSection",
	"RtlUlongByteSwap",
	"RtlUnicodeStringToAnsiString",
	"RtlUnicodeStringToInteger",
	"RtlUnicodeToMultiByteN",
	"RtlUnicodeToMultiByteSize",
	"RtlUnwind",
	"RtlUpcaseUnicodeChar",
	"RtlUpcaseUnicodeString",
	"RtlUpcaseUnicodeToMultiByteN",
	"RtlUpperChar",
	"RtlUpperString",
	"RtlUshortByteSwap",
	"RtlWalkFrameChain",
	"RtlZeroMemory",
	"XboxEEPROMKey",
	"XboxHardwareInfo",
	"XboxHDKey",
	"XboxKrnlVersion",
	"XboxSignatureKey",
	"XeImageFileName",
	"XeLoadSection",
	"XeUnloadSection",
	"READ_PORT_BUFFER_UCHAR",
	"READ_PORT_BUFFER_USHORT",
	"READ_PORT_BUFFER_ULONG",
	"WRITE_PORT_BUFFER_UCHAR",
	"WRITE_PORT_BUFFER_USHORT",
	"WRITE_PORT_BUFFER_ULONG",
	"XcSHAInit",
	"XcSHAUpdate",
	"XcSHAFinal",
	"XcRC4Key",
	"XcRC4Crypt",
	"XcHMAC",
	"XcPKEncPublic",
	"XcPKDecPrivate",
	"XcPKGetKeyLen",
	"XcVerifyPKCS1Signature",
	"XcModExp",
	"XcDESKeyParity",
	"XcKeyTable",
	"XcBlockCrypt",
	"XcBlockCryptCBC",
	"XcCryptService",
	"XcUpdateCrypto",
	"RtlRip",
	"XboxLANKey",
	"XboxAlternateSignatureKeys",
	"XePublicKeyData",
	"HalBootSMCVideoMode",
	"IdexChannelObject",
	"HalIsResetOrShutdownPending",
	"IoMarkIrpMustComplete",
	"HalInitiateShutdown",
	"RtlSnprintf",
	"RtlSprintf",
	"RtlVsnprintf",
	"RtlVsprintf",
	"HalEnableSecureTrayEject",
	"HalWriteSMCScratchRegister",
	"Unknown367",
	"Unknown368",
	"Unknown369",
	"XProfpControl",
	"XProfpGetData",
	"IrtClientInitFast",
	"IrtSweep",
	"MmDbgAllocateMemory",
	"MmDbgFreeMemory",
	"MmDbgQueryAvailablePages",
	"MmDbgReleaseAddress",
	"MmDbgWriteCheck",
    };
}
